<?php
declare(strict_types=1);namespace Vendi\Sales;use PDO;use RuntimeException;use Vendi\Inventory\{LotService,RecipeService};
final class InventoryConsumptionService{public function __construct(private PDO $db,private LotService $lots,private RecipeService $recipes){}
 public function consume(int$b,int$branch,int$u,int$sale,int$item,array$line):void{$pid=(int)$line['product_id'];$qty=(float)($line['qty_base']??$line['qty']??$line['quantity']??0);$vid=!empty($line['variant_id'])?(int)$line['variant_id']:null;if($qty<=0)throw new RuntimeException('Cantidad inválida.');
 $q=$this->db->prepare("SELECT tracks_lots,tracks_serials,expiration_sale_policy FROM products WHERE id=? AND business_id=? FOR UPDATE");$q->execute([$pid,$b]);$p=$q->fetch();if(!$p)throw new RuntimeException('Producto no encontrado.');
 if($vid){$v=$this->db->prepare("UPDATE variant_inventory SET quantity=quantity-? WHERE branch_id=? AND variant_id=? AND quantity>=?");$v->execute([$qty,$branch,$vid,$qty]);if($v->rowCount()!==1)throw new RuntimeException('Existencia insuficiente de la variante.');}
 $inv=$this->db->prepare("UPDATE inventory SET qty=qty-? WHERE business_id=? AND branch_id=? AND product_id=? AND qty>=?");$inv->execute([$qty,$b,$branch,$pid,$qty]);if($inv->rowCount()!==1)throw new RuntimeException('Existencia insuficiente.');
 if((int)$p['tracks_lots']===1){foreach($this->lots->fefo($b,$branch,$pid,$qty) as$l){if($l['expires_at']&&$l['expires_at']<date('Y-m-d')&&$p['expiration_sale_policy']==='block')throw new RuntimeException('El lote '.$l['lot_number'].' está caducado.');$this->db->prepare("UPDATE inventory_lots SET qty_base=qty_base-? WHERE id=? AND qty_base>=?")->execute([$l['qty_base'],$l['lot_id'],$l['qty_base']]);$this->db->prepare("INSERT INTO sale_item_lots(sale_item_id,lot_id,quantity_base) VALUES(?,?,?)")->execute([$item,$l['lot_id'],$l['qty_base']]);}}
 if((int)$p['tracks_serials']===1){$ss=$line['serial_ids']??[];if(count($ss)!==(int)round($qty))throw new RuntimeException('Selecciona una serie por unidad.');foreach($ss as$sid){$s=$this->db->prepare("UPDATE inventory_serials SET status='sold',sale_id=? WHERE id=? AND business_id=? AND branch_id=? AND product_id=? AND status='available'");$s->execute([$sale,(int)$sid,$b,$branch,$pid]);if($s->rowCount()!==1)throw new RuntimeException('Serie no disponible.');$this->db->prepare("INSERT INTO sale_item_serials(sale_item_id,serial_id) VALUES(?,?)")->execute([$item,(int)$sid]);}}
 $this->db->prepare("INSERT INTO stock_movements(business_id,branch_id,product_id,user_id,variant_id,type,qty,reference_type,reference_id) VALUES(?,?,?,?,?,'sale',?,'sale',?)")->execute([$b,$branch,$pid,$u,$vid,-$qty,$sale]);
 foreach($this->recipes->consumption($b,$pid,(float)($line['qty']??$line['quantity']??$qty)) as$c){if($c['optional'])continue;$ci=$this->db->prepare("UPDATE inventory SET qty=qty-? WHERE business_id=? AND branch_id=? AND product_id=? AND qty>=?");$ci->execute([$c['quantity_base'],$b,$branch,$c['product_id'],$c['quantity_base']]);if($ci->rowCount()!==1)throw new RuntimeException('Ingrediente sin existencia suficiente.');$this->db->prepare("INSERT INTO sale_item_components(sale_item_id,component_product_id,component_variant_id,quantity_base) VALUES(?,?,?,?)")->execute([$item,$c['product_id'],$c['variant_id'],$c['quantity_base']]);$this->db->prepare("INSERT INTO stock_movements(business_id,branch_id,product_id,user_id,variant_id,type,qty,reference_type,reference_id) VALUES(?,?,?,?,?,'sale',?,'recipe_sale',?)")->execute([$b,$branch,$c['product_id'],$u,$c['variant_id'],-$c['quantity_base'],$sale]);}}
}}