<?php
declare(strict_types=1);
namespace Vendi\Sales;
use PDO;use RuntimeException;use Vendi\Inventory\{LotService,RecipeService};
final class InventoryConsumptionService{
 public function __construct(private PDO $db,private LotService $lots,private RecipeService $recipes){}
 public function consume(int $businessId,int $branchId,int $userId,int $saleId,int $saleItemId,array $line):void{
  $productId=(int)$line['product_id'];$qtyBase=(float)($line['qty_base']??$line['quantity']??0);$variantId=isset($line['variant_id'])?(int)$line['variant_id']:null;
  $q=$this->db->prepare("SELECT tracks_lots,tracks_expiration,tracks_serials,expiration_sale_policy FROM products WHERE id=? AND business_id=? FOR UPDATE");$q->execute([$productId,$businessId]);$p=$q->fetch();if(!$p)throw new RuntimeException('Producto no encontrado.');
  if($variantId){$v=$this->db->prepare("SELECT quantity FROM variant_inventory WHERE branch_id=? AND variant_id=? FOR UPDATE");$v->execute([$branchId,$variantId]);$stock=(float)($v->fetchColumn()?:0);if($stock<$qtyBase)throw new RuntimeException('Existencia insuficiente de la variante.');$this->db->prepare("UPDATE variant_inventory SET quantity=quantity-? WHERE branch_id=? AND variant_id=?")->execute([$qtyBase,$branchId,$variantId]);}
  $inv=$this->db->prepare("SELECT quantity FROM inventory WHERE branch_id=? AND product_id=? FOR UPDATE");$inv->execute([$branchId,$productId]);$stock=(float)($inv->fetchColumn()?:0);if($stock<$qtyBase)throw new RuntimeException('Existencia insuficiente.');$this->db->prepare("UPDATE inventory SET quantity=quantity-? WHERE branch_id=? AND product_id=?")->execute([$qtyBase,$branchId,$productId]);
  if((int)$p['tracks_lots']===1){foreach($this->lots->fefo($businessId,$branchId,$productId,$qtyBase) as $lot){if($lot['expires_at']&&$lot['expires_at']<date('Y-m-d')&&$p['expiration_sale_policy']==='block')throw new RuntimeException('El lote '.$lot['lot_number'].' está caducado.');$this->db->prepare("UPDATE inventory_lots SET qty_base=qty_base-? WHERE id=?")->execute([$lot['qty_base'],$lot['lot_id']]);$this->db->prepare("INSERT INTO sale_item_lots(sale_item_id,lot_id,quantity_base) VALUES(?,?,?)")->execute([$saleItemId,$lot['lot_id'],$lot['qty_base']]);}}
  if((int)$p['tracks_serials']===1){$serials=$line['serial_ids']??[];if(count($serials)!==(int)round($qtyBase))throw new RuntimeException('Selecciona una serie por unidad.');foreach($serials as $sid){$s=$this->db->prepare("UPDATE inventory_serials SET status='sold',sale_id=? WHERE id=? AND business_id=? AND branch_id=? AND product_id=? AND status='available'");$s->execute([$saleId,(int)$sid,$businessId,$branchId,$productId]);if($s->rowCount()!==1)throw new RuntimeException('Serie no disponible.');$this->db->prepare("INSERT INTO sale_item_serials(sale_item_id,serial_id) VALUES(?,?)")->execute([$saleItemId,(int)$sid]);}}
  $m=$this->db->prepare("INSERT INTO stock_movements(business_id,branch_id,product_id,variant_id,type,quantity,reference_type,reference_id,user_id,created_at) VALUES(?,?,?,?, 'sale',?,'sale',?,?,NOW())");$m->execute([$businessId,$branchId,$productId,$variantId,-$qtyBase,$saleId,$userId]);
  foreach($this->recipes->consumption($businessId,$productId,(float)$line['quantity']) as $c){if($c['optional'])continue;$ci=$this->db->prepare("SELECT quantity FROM inventory WHERE branch_id=? AND product_id=? FOR UPDATE");$ci->execute([$branchId,$c['product_id']]);if((float)($ci->fetchColumn()?:0)<$c['quantity_base'])throw new RuntimeException('Ingrediente sin existencia suficiente.');$this->db->prepare("UPDATE inventory SET quantity=quantity-? WHERE branch_id=? AND product_id=?")->execute([$c['quantity_base'],$branchId,$c['product_id']]);$this->db->prepare("INSERT INTO sale_item_components(sale_item_id,component_product_id,component_variant_id,quantity_base) VALUES(?,?,?,?)")->execute([$saleItemId,$c['product_id'],$c['variant_id'],$c['quantity_base']]);}
 }
}