<?php
declare(strict_types=1);
require dirname(__DIR__).'/vendor/autoload.php';
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Clientes · Vendi POS</title><link rel="stylesheet" href="assets/app.css"></head><body>
<aside><div class="brand">Vendi<span>POS</span></div><nav><a href="index.php">Venta</a><a>Inventario</a><a>Productos</a><a class="active" href="customers.php">Clientes</a><a>Compras</a><a>Proveedores</a><a>Caja</a><a href="reports.php">Reportes</a><a href="invoices.php">Facturación</a><a href="branches.php">Sucursales</a><a href="settings.php">Configuración</a></nav></aside>
<main class="customers-page"><div class="page-head"><div><h1>Clientes</h1><p>Expediente, precios, compras y crédito.</p></div><button id="newCustomer" class="primary-button">＋ Nuevo cliente</button></div>
<div class="customer-toolbar"><input id="customerListSearch" placeholder="Buscar por nombre, teléfono, correo o RFC"></div><section id="customerList" class="customer-list"></section>
<section id="customerDetail" class="customer-detail panel" hidden><div class="customer-detail-head"><div><h2 id="detailName"></h2><p id="detailContact"></p></div><button id="closeDetail">×</button></div><div class="customer-kpis"><article><span>Nivel de precio</span><strong id="detailPriceLevel">Público</strong></article><article><span>Límite de crédito</span><strong id="detailCreditLimit">$0.00</strong></article><article><span>Saldo utilizado</span><strong id="detailCreditBalance">$0.00</strong></article><article><span>Disponible</span><strong id="detailCreditAvailable">$0.00</strong></article></div><div class="customer-tabs"><button data-tab="profile" class="selected">Datos</button><button data-tab="documents">Documentos</button><button data-tab="history">Historial</button></div><div id="customerTabBody"></div></section>
<dialog id="customerDialog"><form id="customerForm" method="dialog"><h2 id="customerFormTitle">Nuevo cliente</h2><input type="hidden" id="customerId"><label>Nombre *<input id="customerName" required></label><label>Correo<input id="customerEmail" type="email"></label><label>Teléfono<input id="customerPhone"></label><label>RFC<input id="customerRfc" maxlength="13"></label><fieldset class="billing-fields"><legend>Datos de facturación</legend><label>Razón social / nombre fiscal<input id="customerTaxName"></label><label>Código postal fiscal<input id="customerTaxZip" maxlength="5" inputmode="numeric"></label><label>Régimen fiscal<input id="customerTaxRegime" maxlength="10" placeholder="Ej. 601, 612, 626"></label><label>Uso de CFDI<input id="customerCfdiUse" maxlength="10" placeholder="Ej. G03, S01"></label></fieldset><label>Nivel de precios<select id="customerPriceLevel"><option value="">Precio público</option></select></label><label class="check-line"><input id="customerCreditEnabled" type="checkbox"> Habilitar crédito</label><label>Límite de crédito<input id="customerCreditLimit" inputmode="decimal" value="0"></label><label>Notas<textarea id="customerNotes"></textarea></label><div class="dialog-actions"><button type="button" id="cancelCustomer">Cancelar</button><button class="primary-button" type="submit">Guardar cliente</button></div></form></dialog>
<script src="assets/customers.js"></script></main></body></html>