<?php
declare(strict_types=1);
require dirname(__DIR__).'/vendor/autoload.php';
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Personal · Vendi POS</title><link rel="stylesheet" href="assets/app.css"></head><body>
<aside><div class="brand">Vendi<span>POS</span></div><nav><a href="index.php">Venta</a><a>Inventario</a><a>Productos</a><a href="customers.php">Clientes</a><a>Compras</a><a>Proveedores</a><a>Caja</a><a href="reports.php">Reportes</a><a href="invoices.php">Facturación</a><a class="active" href="employees.php">Empleados</a><a href="branches.php">Sucursales</a><a href="settings.php">Configuración</a></nav></aside>
<main class="employees-page"><div class="page-head"><div><h1>Personal</h1><p>Desempeño, ventas y comisiones del equipo.</p></div><div class="employee-dates"><input id="empFrom" type="date"><input id="empTo" type="date"><button id="refreshEmployees">Actualizar</button></div></div>
<section class="employee-summary"><article><span>Ventas del equipo</span><strong id="teamSales">$0.00</strong></article><article><span>Tickets</span><strong id="teamTickets">0</strong></article><article><span>Utilidad</span><strong id="teamProfit">$0.00</strong></article><article><span>Comisiones</span><strong id="teamCommissions">$0.00</strong></article></section>
<section class="panel"><div class="employee-tabs"><button data-view="performance" class="selected">Desempeño</button><button data-view="commissions">Comisiones</button></div><div id="employeeContent"></div></section>
<dialog id="commissionDialog"><form id="commissionForm" method="dialog"><h2>Configurar comisión</h2><input id="commissionUserId" type="hidden"><p id="commissionEmployee"></p><label class="check-line"><input id="commissionEnabled" type="checkbox"> Activar comisión</label><label>Calcular sobre<select id="commissionBasis"><option value="sales">Venta</option><option value="profit">Utilidad</option></select></label><label>Porcentaje<input id="commissionRate" type="number" min="0" max="100" step=".01"></label><div class="dialog-actions"><button type="button" id="cancelCommission">Cancelar</button><button class="primary-button" type="submit">Guardar</button></div></form></dialog>
<script src="assets/employees.js"></script></main></body></html>