<?php
declare(strict_types=1);
require dirname(__DIR__).'/vendor/autoload.php';
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Vendi POS</title><link rel="stylesheet" href="assets/app.css"></head><body>
<aside><div class="brand">Vendi<span>POS</span></div><nav><a class="active">Venta</a><a>Inventario</a><a>Productos</a><a>Clientes</a><a>Compras</a><a>Proveedores</a><a>Caja</a><a>Reportes</a><a href="invoices.php">Facturación</a><a href="branches.php">Sucursales</a><a>Periféricos</a><a href="settings.php">Configuración</a></nav></aside>
<main><header><div><b>Punto de venta</b><small><select id="activeBranch" class="branch-selector"><option>Cargando sucursales…</option></select> <span id="branchLocalClock"></span> · Caja</small></div><div class="header-actions"><div class="sale-menu-wrap"><button id="openSalesBtn" class="menu-button">Ventas abiertas <span id="openSalesCount">0</span></button><button id="saleMenuBtn" class="menu-button">Operaciones ▾</button><div id="saleMenu" class="sale-menu" hidden><a href="sales.php">⌕ Buscar tickets anteriores</a><button data-cash-action="expense">− Agregar gasto</button><button data-cash-action="deposit">＋ Agregar efectivo a caja</button><button data-cash-action="count">▦ Arqueo de caja</button><button data-cash-action="close">✓ Cierre de caja</button></div></div><span id="scaleStatus" class="status">⚖ Sin báscula</span><button id="connectScale">Conectar</button></div></header>
<div id="shortcutMessage" class="toast" hidden></div><section class="tabs" id="saleTabs"></section>
<section class="shortcuts"><span>F2 Cobrar</span><span>F3 Guardar</span><span class="fast">F4 Venta rápida</span><span>F6 Cliente</span><span>F9 Cantidad</span></section>
<section class="pos"><div class="catalog"><div class="search">⌕ <div class="product-search-wrap"><input id="productSearch" autocomplete="off" placeholder="Buscar producto, SKU o escanear código"><div id="searchResults" class="search-results" hidden></div></div><input id="customerSearch" class="customer" placeholder="Cliente"></div><div class="qtybar"><input id="qty" inputmode="decimal" placeholder="Cantidad o 4.25+3.80+6.10"><button id="qtyCalc">=</button><b id="scaleWeight"></b></div><div class="empty"><h2>Comienza una venta</h2><p>Escanea un producto o búscalo por nombre.</p></div></div>
<div class="cart"><h3>Venta actual <span id="cartCount">0 artículos</span></h3><div id="cartItems" class="cart-items"></div><div class="totals"><p>Subtotal <b id="cartSubtotal">$0.00</b></p><p>Descuento <b id="cartDiscount">$0.00</b></p><p>IVA <b id="cartTax">$0.00</b></p><h2>Total <b id="cartTotal">$0.00</b></h2></div><button id="quickFinish" class="charge" disabled>F4 · Terminar venta rápida</button></div></section></main>
<div id="checkoutModal" class="modal" hidden><div class="modal-card"><div class="modal-head"><h2>Cobrar venta</h2><button data-close="checkoutModal">×</button></div><div class="checkout-total"><small>Total</small><strong id="checkoutTotal">$0.00</strong></div><div id="paymentMethods" class="pay-grid"></div><div id="paymentLines" class="payment-lines"></div><div class="payment-balance"><span>Por asignar <b id="paymentRemaining">$0.00</b></span><span>Cambio <b id="cashChange">$0.00</b></span></div><button id="confirmCheckout" class="confirm">Confirmar cobro</button></div></div>
<div id="cashModal" class="modal" hidden><div class="modal-card"><div class="modal-head"><h2 id="cashModalTitle">Caja</h2><button data-close="cashModal">×</button></div><div id="cashSummary" class="cash-summary"></div><label id="cashAmountLabel">Importe<input id="cashAmount" inputmode="decimal" placeholder="0.00"></label><label id="cashNoteLabel">Concepto / motivo<input id="cashNote" maxlength="255" placeholder="Escribe el motivo"></label><button id="cashConfirm" class="confirm">Guardar</button></div></div>
<div id="openSalesModal" class="modal" hidden><div class="modal-card"><div class="modal-head"><h2>Ventas abiertas</h2><button data-close="openSalesModal">×</button></div><div id="openSalesList" class="open-sales-list"></div></div></div><div id="productConfigurator" class="modal" hidden><div class="modal-card pc-card"><div class="modal-head"><div><h2 id="pcTitle">Configurar producto</h2><p id="pcSubtitle"></p></div><button id="pcClose">×</button></div><div id="pcBody"></div><div class="pc-actions"><button id="pcCancel" class="menu-button">Cancelar</button><button id="pcConfirm" class="primary-button">Agregar a venta</button></div></div></div><script src="assets/branch_context.js"></script><script src="assets/product_configurator.js"></script><script src="assets/pos.js"></script></body></html>