<?php
declare(strict_types=1);
namespace Vendi\Reports;
use PDO;use Vendi\Branches\BranchClock;
final class CashPaymentReportService{
 public function __construct(private PDO $db){}
 private function range(int$b,int$branch,string$from,string$to):array{$c=new BranchClock($this->db);[$a]=$c->utcRangeForLocalDate($b,$branch,$from);[, $z]=$c->utcRangeForLocalDate($b,$branch,$to);return[$a,$z];}
 public function payments(int$b,int$branch,string$from,string$to):array{[$a,$z]=$this->range($b,$branch,$from,$to);$q=$this->db->prepare("SELECT p.id,s.id sale_id,COALESCE(pm.name,p.method) method,p.amount,p.change_amount,(p.amount-p.change_amount) net_amount,p.reference,p.created_at,u.name cashier FROM payments p JOIN sales s ON s.id=p.sale_id JOIN users u ON u.id=s.user_id LEFT JOIN payment_methods pm ON pm.id=p.payment_method_id WHERE s.business_id=? AND s.branch_id=? AND s.status='completed' AND s.completed_at_utc>=? AND s.completed_at_utc<? ORDER BY p.created_at DESC LIMIT 1000");$q->execute([$b,$branch,$a,$z]);return$q->fetchAll();}
 public function overview(int$b,int$branch,string$from,string$to):array{[$a,$z]=$this->range($b,$branch,$from,$to);$q=$this->db->prepare("SELECT COALESCE(pm.name,p.method) method,COUNT(*) movements,SUM(p.amount) received,SUM(p.change_amount) change_total,SUM(p.amount-p.change_amount) net_total FROM payments p JOIN sales s ON s.id=p.sale_id LEFT JOIN payment_methods pm ON pm.id=p.payment_method_id WHERE s.business_id=? AND s.branch_id=? AND s.status='completed' AND s.completed_at_utc>=? AND s.completed_at_utc<? GROUP BY COALESCE(pm.name,p.method) ORDER BY net_total DESC");$q->execute([$b,$branch,$a,$z]);return$q->fetchAll();}
 public function byRegister(int$b,int$branch,string$from,string$to):array{[$a,$z]=$this->range($b,$branch,$from,$to);$q=$this->db->prepare("SELECT COALESCE(cr.name,'Sin caja asignada') register_name,COUNT(DISTINCT p.sale_id) tickets,SUM(p.amount-p.change_amount) total FROM payments p JOIN sales s ON s.id=p.sale_id LEFT JOIN cash_sessions cs ON cs.id=p.cash_session_id LEFT JOIN cash_registers cr ON cr.id=cs.cash_register_id WHERE s.business_id=? AND s.branch_id=? AND s.status='completed' AND s.completed_at_utc>=? AND s.completed_at_utc<? GROUP BY cr.id,cr.name ORDER BY total DESC");$q->execute([$b,$branch,$a,$z]);return$q->fetchAll();}
 public function closeouts(int$b,int$branch,string$from,string$to):array{[$a,$z]=$this->range($b,$branch,$from,$to);$q=$this->db->prepare("SELECT cs.id,COALESCE(cr.name,'Caja') register_name,u.name cashier,cs.opening_amount,cs.expected_amount,cs.closing_amount,cs.difference_amount,cs.opened_at_utc,cs.closed_at_utc,cs.status FROM cash_sessions cs JOIN users u ON u.id=cs.user_id LEFT JOIN cash_registers cr ON cr.id=cs.cash_register_id WHERE cs.business_id=? AND cs.branch_id=? AND cs.opened_at_utc>=? AND cs.opened_at_utc<? ORDER BY cs.id DESC LIMIT 500");$q->execute([$b,$branch,$a,$z]);return$q->fetchAll();}
 public function movements(int$b,int$branch,string$from,string$to):array{[$a,$z]=$this->range($b,$branch,$from,$to);$q=$this->db->prepare("SELECT cm.id,COALESCE(cr.name,'Caja') register_name,u.name cashier,cm.type,cm.amount,cm.reference_type,cm.reference_id,cm.note,cm.created_at FROM cash_movements cm JOIN users u ON u.id=cm.user_id LEFT JOIN cash_sessions cs ON cs.id=cm.cash_session_id LEFT JOIN cash_registers cr ON cr.id=cs.cash_register_id WHERE cm.business_id=? AND cm.branch_id=? AND cm.created_at>=? AND cm.created_at<? ORDER BY cm.created_at DESC LIMIT 1000");$q->execute([$b,$branch,$a,$z]);return$q->fetchAll();}
}