<?php
declare(strict_types=1);
namespace Vendi\Reports;
use PDO;use Vendi\Branches\BranchClock;
final class FinanceReportService{
 public function __construct(private PDO $db){}
 private function range(int$b,int$branch,string$f,string$t):array{$c=new BranchClock($this->db);[$a]=$c->utcRangeForLocalDate($b,$branch,$f);[, $z]=$c->utcRangeForLocalDate($b,$branch,$t);return[$a,$z];}
 public function profitLoss(int$b,int$branch,string$f,string$t):array{[$a,$z]=$this->range($b,$branch,$f,$t);$s=$this->db->prepare("SELECT COALESCE(SUM(total),0) sales,COALESCE(SUM(cost_total),0) cost_of_sales,COALESCE(SUM(discount),0) discounts,COALESCE(SUM(tax),0) sales_tax FROM sales WHERE business_id=? AND branch_id=? AND status='completed' AND completed_at_utc>=? AND completed_at_utc<?");$s->execute([$b,$branch,$a,$z]);$x=$s->fetch();$e=$this->db->prepare("SELECT COALESCE(SUM(subtotal),0) expense_subtotal,COALESCE(SUM(tax),0) expense_tax,COALESCE(SUM(total),0) expenses FROM expenses WHERE business_id=? AND branch_id=? AND occurred_at_utc>=? AND occurred_at_utc<?");$e->execute([$b,$branch,$a,$z]);$x=array_merge($x,$e->fetch());$x['gross_profit']=(float)$x['sales']-(float)$x['cost_of_sales'];$x['operating_result']=$x['gross_profit']-(float)$x['expenses'];return[$x];}
 public function expenses(int$b,int$branch,string$f,string$t):array{[$a,$z]=$this->range($b,$branch,$f,$t);$q=$this->db->prepare("SELECT e.id,e.occurred_at_utc,e.category,e.description,e.subtotal,e.tax,e.total,e.payment_method,e.reference,u.name employee FROM expenses e JOIN users u ON u.id=e.user_id WHERE e.business_id=? AND e.branch_id=? AND e.occurred_at_utc>=? AND e.occurred_at_utc<? ORDER BY e.occurred_at_utc DESC");$q->execute([$b,$branch,$a,$z]);return$q->fetchAll();}
 public function expenseOverview(int$b,int$branch,string$f,string$t):array{[$a,$z]=$this->range($b,$branch,$f,$t);$q=$this->db->prepare("SELECT category,COUNT(*) movements,SUM(subtotal) subtotal,SUM(tax) tax,SUM(total) total FROM expenses WHERE business_id=? AND branch_id=? AND occurred_at_utc>=? AND occurred_at_utc<? GROUP BY category ORDER BY total DESC");$q->execute([$b,$branch,$a,$z]);return$q->fetchAll();}
 public function taxes(int$b,int$branch,string$f,string$t):array{[$a,$z]=$this->range($b,$branch,$f,$t);$q=$this->db->prepare("SELECT 'IVA trasladado en ventas' concept,COALESCE(SUM(tax),0) amount FROM sales WHERE business_id=? AND branch_id=? AND status='completed' AND completed_at_utc>=? AND completed_at_utc<? UNION ALL SELECT 'Impuesto registrado en gastos',COALESCE(SUM(tax),0) FROM expenses WHERE business_id=? AND branch_id=? AND occurred_at_utc>=? AND occurred_at_utc<?");$q->execute([$b,$branch,$a,$z,$b,$branch,$a,$z]);return$q->fetchAll();}
 public function invoices(int$b,int$branch,string$f,string$t):array{[$a,$z]=$this->range($b,$branch,$f,$t);$q=$this->db->prepare("SELECT i.id,i.sale_id,i.rfc,i.tax_name,i.uuid,i.status,i.subtotal,i.total,i.created_at,i.stamped_at FROM invoices i JOIN sales s ON s.id=i.sale_id WHERE i.business_id=? AND i.branch_id=? AND s.completed_at_utc>=? AND s.completed_at_utc<? ORDER BY i.id DESC");$q->execute([$b,$branch,$a,$z]);return$q->fetchAll();}
}