<?php
declare(strict_types=1);
namespace Vendi\Reports;
use PDO;use Vendi\Branches\BranchClock;
final class PurchaseSupplierReportService{
 public function __construct(private PDO $db){}
 private function range(int$b,int$branch,string$from,string$to):array{$c=new BranchClock($this->db);[$a]=$c->utcRangeForLocalDate($b,$branch,$from);[, $z]=$c->utcRangeForLocalDate($b,$branch,$to);return[$a,$z];}
 public function purchases(int$b,int$branch,string$from,string$to):array{[$a,$z]=$this->range($b,$branch,$from,$to);$q=$this->db->prepare("SELECT po.id,po.folio,s.name supplier,po.status,po.subtotal,po.tax,po.total,po.ordered_at,po.expected_at,po.created_at FROM purchase_orders po JOIN suppliers s ON s.id=po.supplier_id WHERE po.business_id=? AND po.branch_id=? AND po.created_at>=? AND po.created_at<? ORDER BY po.created_at DESC LIMIT 1000");$q->execute([$b,$branch,$a,$z]);return$q->fetchAll();}
 public function suppliers(int$b,int$branch):array{$q=$this->db->prepare("SELECT s.id,s.name,COUNT(DISTINCT po.id) orders,COALESCE(SUM(po.total),0) purchased,MAX(po.created_at) last_purchase FROM suppliers s LEFT JOIN purchase_orders po ON po.supplier_id=s.id AND po.business_id=s.business_id AND po.branch_id=? AND po.status<>'cancelled' WHERE s.business_id=? GROUP BY s.id,s.name ORDER BY purchased DESC,s.name");$q->execute([$branch,$b]);return$q->fetchAll();}
 public function products(int$b,int$branch,string$from,string$to):array{[$a,$z]=$this->range($b,$branch,$from,$to);$q=$this->db->prepare("SELECT p.name,COALESCE(pc.name,'Sin categoría') category,SUM(pri.qty_received) qty_received,SUM(pri.qty_received*pri.presentation_cost) total_cost,AVG(pri.presentation_cost) average_receipt_cost FROM purchase_receipt_items pri JOIN purchase_receipts pr ON pr.id=pri.receipt_id JOIN products p ON p.id=pri.product_id LEFT JOIN product_categories pc ON pc.id=p.category_id WHERE pr.business_id=? AND pr.branch_id=? AND pr.received_at>=? AND pr.received_at<? GROUP BY p.id,p.name,pc.name ORDER BY total_cost DESC");$q->execute([$b,$branch,$a,$z]);return$q->fetchAll();}
 public function supplierCost(int$b,int$branch):array{$q=$this->db->prepare("SELECT p.name product,s.name supplier,SUM(pri.qty_received) qty_received,AVG(pri.presentation_cost) average_cost,MIN(pri.presentation_cost) lowest_cost,MAX(pri.presentation_cost) highest_cost,MAX(pr.received_at) last_receipt FROM purchase_receipt_items pri JOIN purchase_receipts pr ON pr.id=pri.receipt_id JOIN suppliers s ON s.id=pr.supplier_id JOIN products p ON p.id=pri.product_id WHERE pr.business_id=? AND pr.branch_id=? GROUP BY p.id,p.name,s.id,s.name ORDER BY p.name,average_cost");$q->execute([$b,$branch]);return$q->fetchAll();}
 public function categories(int$b,int$branch,string$from,string$to):array{[$a,$z]=$this->range($b,$branch,$from,$to);$q=$this->db->prepare("SELECT COALESCE(pc.name,'Sin categoría') category,SUM(pri.qty_received) qty_received,SUM(pri.qty_received*pri.presentation_cost) total FROM purchase_receipt_items pri JOIN purchase_receipts pr ON pr.id=pri.receipt_id JOIN products p ON p.id=pri.product_id LEFT JOIN product_categories pc ON pc.id=p.category_id WHERE pr.business_id=? AND pr.branch_id=? AND pr.received_at>=? AND pr.received_at<? GROUP BY pc.id,pc.name ORDER BY total DESC");$q->execute([$b,$branch,$a,$z]);return$q->fetchAll();}
 public function taxes(int$b,int$branch,string$from,string$to):array{[$a,$z]=$this->range($b,$branch,$from,$to);$q=$this->db->prepare("SELECT COUNT(*) orders,COALESCE(SUM(subtotal),0) subtotal,COALESCE(SUM(tax),0) tax,COALESCE(SUM(total),0) total FROM purchase_orders WHERE business_id=? AND branch_id=? AND status<>'cancelled' AND created_at>=? AND created_at<?");$q->execute([$b,$branch,$a,$z]);return$q->fetchAll();}
 public function transfers(int$b,int$branch):array{$q=$this->db->prepare("SELECT st.id,fb.name origin,tb.name destination,st.status,st.sent_at,st.received_at,st.created_at FROM stock_transfers st JOIN branches fb ON fb.id=st.from_branch_id JOIN branches tb ON tb.id=st.to_branch_id WHERE st.business_id=? AND (st.from_branch_id=? OR st.to_branch_id=?) ORDER BY st.created_at DESC LIMIT 500");$q->execute([$b,$branch,$branch]);return$q->fetchAll();}
}