<?php
declare(strict_types=1);
namespace Vendi\Reports;
use PDO;use Vendi\Branches\BranchClock;
final class SalesReportService{
 public function __construct(private PDO $db){}
 private function range(int $b,int $branch,string $from,string $to):array{$c=new BranchClock($this->db);[$a]=$c->utcRangeForLocalDate($b,$branch,$from);[, $z]=$c->utcRangeForLocalDate($b,$branch,$to);return[$a,$z,$c];}
 public function movements(int $b,int $branch,string $from,string $to,int $limit=250):array{[$a,$z,$c]=$this->range($b,$branch,$from,$to);$limit=max(1,min(1000,$limit));$q=$this->db->prepare("SELECT s.id,s.completed_at_utc,s.subtotal,s.discount,s.tax,s.total,s.cost_total,(s.total-s.cost_total) profit,u.name cashier,COALESCE(cu.name,'Público general') customer FROM sales s JOIN users u ON u.id=s.user_id LEFT JOIN customers cu ON cu.id=s.customer_id WHERE s.business_id=? AND s.branch_id=? AND s.status='completed' AND s.completed_at_utc>=? AND s.completed_at_utc<? ORDER BY s.completed_at_utc DESC LIMIT ".$limit);$q->execute([$b,$branch,$a,$z]);return['rows'=>$q->fetchAll(),'timezone'=>$c->timezone($b,$branch)->getName()];}
 public function byWeekday(int $b,int $branch,string $from,string $to):array{[$a,$z]=$this->range($b,$branch,$from,$to);$q=$this->db->prepare("SELECT DAYOFWEEK(completed_at_utc) weekday,COUNT(*) tickets,SUM(total) sales,SUM(total-cost_total) profit FROM sales WHERE business_id=? AND branch_id=? AND status='completed' AND completed_at_utc>=? AND completed_at_utc<? GROUP BY DAYOFWEEK(completed_at_utc) ORDER BY weekday");$q->execute([$b,$branch,$a,$z]);return $q->fetchAll();}
 public function byHour(int $b,int $branch,string $from,string $to):array{[$a,$z]=$this->range($b,$branch,$from,$to);$q=$this->db->prepare("SELECT HOUR(completed_at_utc) hour,COUNT(*) tickets,SUM(total) sales,SUM(total-cost_total) profit FROM sales WHERE business_id=? AND branch_id=? AND status='completed' AND completed_at_utc>=? AND completed_at_utc<? GROUP BY HOUR(completed_at_utc) ORDER BY hour");$q->execute([$b,$branch,$a,$z]);return $q->fetchAll();}
 public function cancelled(int $b,int $branch,string $from,string $to):array{[$a,$z]=$this->range($b,$branch,$from,$to);$q=$this->db->prepare("SELECT s.id,s.created_at,s.total,u.name cashier,COALESCE(cu.name,'Público general') customer FROM sales s JOIN users u ON u.id=s.user_id LEFT JOIN customers cu ON cu.id=s.customer_id WHERE s.business_id=? AND s.branch_id=? AND s.status='cancelled' AND s.created_at>=? AND s.created_at<? ORDER BY s.created_at DESC");$q->execute([$b,$branch,$a,$z]);return $q->fetchAll();}
 public function held(int $b,int $branch):array{$q=$this->db->prepare("SELECT s.id,s.created_at,s.total,u.name cashier,COALESCE(cu.name,'Público general') customer FROM sales s JOIN users u ON u.id=s.user_id LEFT JOIN customers cu ON cu.id=s.customer_id WHERE s.business_id=? AND s.branch_id=? AND s.status='open' ORDER BY s.created_at DESC");$q->execute([$b,$branch]);return $q->fetchAll();}
}