<?php
declare(strict_types=1);namespace Vendi\Branches;use PDO;use RuntimeException;
final class BranchService{public function __construct(private PDO$db){}
 public function all(int$b):array{$q=$this->db->prepare("SELECT b.*,COUNT(ub.user_id) user_count FROM branches b LEFT JOIN user_branches ub ON ub.branch_id=b.id WHERE b.business_id=? GROUP BY b.id ORDER BY b.status='active' DESC,b.name");$q->execute([$b]);return$q->fetchAll();}
 public function one(int$b,int$id):array{$q=$this->db->prepare("SELECT * FROM branches WHERE id=? AND business_id=? LIMIT 1");$q->execute([$id,$b]);$r=$q->fetch();if(!$r)throw new RuntimeException('Sucursal no encontrada.');return$r;}
 public function update(int$b,int$id,array$d):void{$tz=(string)($d['timezone']??'America/Mexico_City');if(!in_array($tz,timezone_identifiers_list(),true))throw new RuntimeException('Zona horaria inválida.');$fields=['name','legal_name','address_line1','address_line2','neighborhood','city','state','postal_code','country_code','phone','phone_alt','email','timezone','locale','currency'];$sets=[];$vals=[];foreach($fields as$x)if(array_key_exists($x,$d)){$sets[]="$x=?";$vals[]=trim((string)$d[$x])?:null;}if(!$sets)throw new RuntimeException('No hay cambios.');$vals[]=$id;$vals[]=$b;$q=$this->db->prepare("UPDATE branches SET ".implode(',',$sets)." WHERE id=? AND business_id=?");$q->execute($vals);if(!$q->rowCount()&&!$this->one($b,$id))throw new RuntimeException('Sucursal no encontrada.');}
 public function setActivation(int$b,int$id,string$status,int$actor):void{if(!in_array($status,['active','suspended'],true))throw new RuntimeException('Estado de activación inválido.');$addon=$status==='active'?'active':'past_due';$q=$this->db->prepare("UPDATE branches SET status=?,addon_status=?,activated_at=IF(?='active',COALESCE(activated_at,NOW()),activated_at),activated_by=IF(?='active',?,activated_by),last_license_check_at=NOW() WHERE id=? AND business_id=?");$q->execute([$status,$addon,$status,$status,$actor,$id,$b]);if(!$q->rowCount())throw new RuntimeException('Sucursal no encontrada.');}
 public function localNow(int$b,int$id):string{$r=$this->one($b,$id);return(new \DateTimeImmutable('now',new \DateTimeZone($r['timezone'])))->format(DATE_ATOM);}
 public function create(int$b,array$d):int{$name=trim((string)($d['name']??''));$code=strtolower(trim((string)($d['code']??'')));if($name===''||$code==='')throw new RuntimeException('Nombre y clave son obligatorios.');if(!preg_match('/^[a-z0-9_-]{2,40}$/',$code))throw new RuntimeException('Clave de sucursal inválida.');$q=$this->db->prepare("INSERT INTO branches(business_id,code,name,status,is_billable_addon,addon_status) VALUES(?,?,?,'pending',1,'pending')");$q->execute([$b,$code,$name]);return(int)$this->db->lastInsertId();}
 public function assigned(int$b,int$userId):array{$q=$this->db->prepare("SELECT b.id,b.name,b.code,b.status,COALESCE(ub.is_default,0) is_default,(ub.user_id IS NOT NULL) assigned FROM branches b LEFT JOIN user_branches ub ON ub.branch_id=b.id AND ub.user_id=? WHERE b.business_id=? ORDER BY b.name");$q->execute([$userId,$b]);return$q->fetchAll();}
 public function assign(int$b,int$userId,array$branchIds,int$defaultId):void{$uq=$this->db->prepare("SELECT id FROM users WHERE id=? AND business_id=?");$uq->execute([$userId,$b]);if(!$uq->fetchColumn())throw new RuntimeException('Usuario no encontrado.');$branchIds=array_values(array_unique(array_map('intval',$branchIds)));if(!$branchIds||!in_array($defaultId,$branchIds,true))throw new RuntimeException('Selecciona al menos una sucursal y una predeterminada.');$marks=implode(',',array_fill(0,count($branchIds),'?'));$q=$this->db->prepare("SELECT id FROM branches WHERE business_id=? AND id IN ($marks) AND status IN ('active','pending')");$q->execute(array_merge([$b],$branchIds));if(count($q->fetchAll())!==count($branchIds))throw new RuntimeException('Una sucursal no pertenece al negocio o no está disponible.');$this->db->beginTransaction();try{$this->db->prepare("DELETE FROM user_branches WHERE user_id=?")->execute([$userId]);$i=$this->db->prepare("INSERT INTO user_branches(user_id,branch_id,is_default) VALUES(?,?,?)");foreach($branchIds as$id)$i->execute([$userId,$id,$id===$defaultId?1:0]);$this->db->prepare("UPDATE users SET default_branch_id=? WHERE id=? AND business_id=?")->execute([$defaultId,$userId,$b]);$this->db->commit();}catch(\Throwable$e){$this->db->rollBack();throw$e;}}
}