<?php
declare(strict_types=1);namespace Vendi\Risk;use PDO;use Vendi\Branches\BranchClock;
final class RiskService{public function __construct(private PDO$db){}
 private function add(int$b,?int$branch,?int$user,string$type,string$severity,string$title,string$detail,?float$amount,?string$entityType,?int$entityId,string$fingerprint):void{$utc=$branch?(new BranchClock($this->db))->utcSql($b,$branch):gmdate('Y-m-d H:i:s');$q=$this->db->prepare("INSERT IGNORE INTO risk_events(business_id,branch_id,user_id,event_type,severity,entity_type,entity_id,title,detail,amount,fingerprint,created_at_utc) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)");$q->execute([$b,$branch,$user,$type,$severity,$entityType,$entityId,$title,$detail,$amount,hash('sha256',$fingerprint),$utc]);}
 public function scan(int$b,array$branches):void{foreach($branches as$br){$branch=(int)$br['id'];$clock=new BranchClock($this->db);$date=$clock->now($b,$branch)->format('Y-m-d');[$from,$to]=$clock->utcRangeForLocalDate($b,$branch,$date);
 $q=$this->db->prepare("SELECT sv.id,sv.sale_id,sv.user_id,sv.reason,sv.created_at FROM sale_voids sv WHERE sv.business_id=? AND sv.branch_id=? AND sv.created_at>=?");$q->execute([$b,$branch,$from]);foreach($q->fetchAll()as$r)$this->add($b,$branch,(int)$r['user_id'],'sale_void','high','Venta cancelada','Cancelación #'.$r['sale_id'].': '.$r['reason'],null,'sale',(int)$r['sale_id'],'void:'.$r['id']);
 $q=$this->db->prepare("SELECT r.id,r.sale_id,r.user_id,r.total,r.reason,r.created_at FROM refunds r WHERE r.business_id=? AND r.branch_id=? AND r.status='completed' AND r.created_at>=?");$q->execute([$b,$branch,$from]);foreach($q->fetchAll()as$r)$this->add($b,$branch,(int)$r['user_id'],'refund',(float)$r['total']>=1000?'high':'medium','Devolución registrada','Venta #'.$r['sale_id'].': '.$r['reason'],(float)$r['total'],'refund',(int)$r['id'],'refund:'.$r['id']);
 $q=$this->db->prepare("SELECT id,user_id,difference_amount FROM cash_sessions WHERE business_id=? AND branch_id=? AND status='closed' AND closed_at_utc>=? AND ABS(difference_amount)>=50");$q->execute([$b,$branch,$from]);foreach($q->fetchAll()as$r)$this->add($b,$branch,(int)$r['user_id'],'cash_difference',abs((float)$r['difference_amount'])>=500?'critical':'high','Diferencia en cierre de caja','Diferencia detectada al realizar el arqueo.',(float)$r['difference_amount'],'cash_session',(int)$r['id'],'cashdiff:'.$r['id']);
 $q=$this->db->prepare("SELECT id,user_id,product_id,old_cost,new_cost FROM product_cost_history WHERE business_id=? AND branch_id=? AND created_at>=? AND old_cost>0 AND ABS(new_cost-old_cost)/old_cost>=.20");$q->execute([$b,$branch,$from]);foreach($q->fetchAll()as$r){$pct=((float)$r['new_cost']-(float)$r['old_cost'])/(float)$r['old_cost']*100;$this->add($b,$branch,(int)$r['user_id'],'cost_change',abs($pct)>=50?'high':'medium','Cambio fuerte de costo','Producto #'.$r['product_id'].' cambió '.round($pct,1).'%.',null,'product',(int)$r['product_id'],'cost:'.$r['id']);}
 $q=$this->db->prepare("SELECT s.user_id,COUNT(*) qty,COALESCE(SUM(s.discount),0) discounts FROM sales s WHERE s.business_id=? AND s.branch_id=? AND s.status='completed' AND s.completed_at_utc>=? AND s.completed_at_utc<? AND s.discount>0 GROUP BY s.user_id HAVING COUNT(*)>=3 OR SUM(s.discount)>=500");$q->execute([$b,$branch,$from,$to]);foreach($q->fetchAll()as$r)$this->add($b,$branch,(int)$r['user_id'],'discount_pattern','medium','Descuentos inusuales',$r['qty'].' ventas con descuento; acumulado $'.number_format((float)$r['discounts'],2), (float)$r['discounts'], 'user',(int)$r['user_id'],'discount:'.$date.':'.$branch.':'.$r['user_id']);
 }}
 public function open(int$b,int$limit=30):array{$q=$this->db->prepare("SELECT re.*,b.name branch_name,u.name user_name FROM risk_events re LEFT JOIN branches b ON b.id=re.branch_id LEFT JOIN users u ON u.id=re.user_id WHERE re.business_id=? AND re.status='open' ORDER BY FIELD(re.severity,'critical','high','medium','low','info'),re.created_at_utc DESC LIMIT ?");$q->bindValue(1,$b,PDO::PARAM_INT);$q->bindValue(2,$limit,PDO::PARAM_INT);$q->execute();return$q->fetchAll();}
 public function review(int$b,int$id,int$reviewer,string$status):void{if(!in_array($status,['reviewed','dismissed','resolved'],true))throw new \RuntimeException('Estado inválido.');$q=$this->db->prepare("UPDATE risk_events SET status=?,reviewed_by=?,reviewed_at=NOW() WHERE id=? AND business_id=? AND status='open'");$q->execute([$status,$reviewer,$id,$b]);}
}